# Generated by Django 6.0.7 on 2026-07-25 05:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField()),
                ('barangay', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=20)),
                ('total_beneficiaries', models.IntegerField(default=0)),
                ('total_released', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grocery_distributions',
            },
        ),
        migrations.CreateModel(
            name='MedicineBooklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklet_number', models.CharField(max_length=50, unique=True)),
                ('date_issued', models.DateField()),
                ('place_issued', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medicine_booklets',
            },
        ),
        migrations.CreateModel(
            name='SeniorCitizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osca_id', models.CharField(max_length=20, unique=True)),
                ('registration_cert_no', models.CharField(max_length=20, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('others', 'Others')], max_length=20)),
                ('address', models.TextField()),
                ('barangay', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('educational_attainment', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_skills', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='senior_photos/')),
                ('association_name', models.CharField(blank=True, max_length=200)),
                ('association_address', models.TextField(blank=True)),
                ('date_of_membership', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('date_of_registration', models.DateField(auto_now_add=True)),
                ('issued_at', models.CharField(blank=True, max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('milestone_age', models.IntegerField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'senior_citizens',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('head_staff', 'Head Staff'), ('regular_staff', 'Regular Staff'), ('senior', 'Senior Citizen'), ('family', 'Family Member')], default='regular_staff', max_length=20)),
                ('must_change_password', models.BooleanField(default=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('senior_citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='core.seniorcitizen')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('upload', 'Upload'), ('search', 'Search'), ('approve', 'Approve')], max_length=20)),
                ('module', models.CharField(max_length=50)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('qty_prescribed', models.IntegerField()),
                ('physician_name', models.CharField(max_length=200)),
                ('physician_address', models.TextField(blank=True)),
                ('ptr_number', models.CharField(max_length=50)),
                ('balance', models.IntegerField(default=0)),
                ('prescription_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('filling_1_qty', models.IntegerField(blank=True, null=True)),
                ('filling_1_date', models.DateField(blank=True, null=True)),
                ('filling_1_drugstore', models.CharField(blank=True, max_length=200)),
                ('filling_1_pharmacist', models.CharField(blank=True, max_length=200)),
                ('filling_2_qty', models.IntegerField(blank=True, null=True)),
                ('filling_2_date', models.DateField(blank=True, null=True)),
                ('filling_2_drugstore', models.CharField(blank=True, max_length=200)),
                ('filling_2_pharmacist', models.CharField(blank=True, max_length=200)),
                ('filling_3_qty', models.IntegerField(blank=True, null=True)),
                ('filling_3_date', models.DateField(blank=True, null=True)),
                ('filling_3_drugstore', models.CharField(blank=True, max_length=200)),
                ('filling_3_pharmacist', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booklet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.medicinebooklet')),
            ],
            options={
                'db_table': 'medicine_prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PensionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('claimed', models.BooleanField(default=False)),
                ('date_claimed', models.DateField(blank=True, null=True)),
                ('claimed_by', models.CharField(default='self', max_length=20)),
                ('representative', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('senior_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_records', to='core.seniorcitizen')),
            ],
            options={
                'db_table': 'pension_records',
            },
        ),
        migrations.AddField(
            model_name='medicinebooklet',
            name='senior_citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_booklets', to='core.seniorcitizen'),
        ),
        migrations.CreateModel(
            name='GroceryClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed', models.BooleanField(default=False)),
                ('date_claimed', models.DateField(blank=True, null=True)),
                ('claimed_by', models.CharField(default='self', max_length=20)),
                ('representative', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.grocerydistribution')),
                ('senior_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_claims', to='core.seniorcitizen')),
            ],
            options={
                'db_table': 'grocery_claims',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('senior_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='core.seniorcitizen')),
            ],
            options={
                'db_table': 'family_members',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_name', models.CharField(max_length=200)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('nlp_classification', models.CharField(blank=True, max_length=100)),
                ('nlp_confidence', models.FloatField(blank=True, null=True)),
                ('extracted_entities', models.JSONField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('senior_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.seniorcitizen')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
